name: flutter_html_view
description: Flutter Plugin to render html, Flutter has no default support to render html so this package helps you to render your html to native widgets
version: 0.5.12
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlView

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.0.2
  html: ^0.15.0
  video_player: ^1.0.1
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  flutter_markdown: ^0.6.3
  html2md: ^1.2.5

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
